[tool.poetry]
name = "zhquiz"
version = "0.1.0"
description = ""
authors = ["Pacharapol Withayasakpunt <polv@polv.cc>"]

[tool.poetry.dependencies]
python = "^3.8.6"
fastapi = "^0.63.0"
uvicorn = "^0.13.2"
wordfreq = "^2.3.2"
jieba = "^0.42.1"

[tool.poetry.dev-dependencies]
pylint = "^2.6.0"
black = {version = "^20.8b1", allow-prereleases = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
