services:
  zhquiz:
    build: .
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      # See https://magic.link for signing in and authorization
      - MAGIC_PUBLIC
      - MAGIC_SECRET
      - PORT=35594
      - SERVER_PORT # For development
    ports:
      - 5433:5432
      # - 35594:35594
      - 35595:35595
    volumes:
      - zhquiz:/var/lib/postgresql/data
      - ./node_modules:/app/node_modules
      - ./server:/app/server
      - ./types:/app/types
    entrypoint: |
      /bin/bash -c "
        /usr/local/bin/docker-entrypoint.sh postgres &
        yarn nodemon server/api/index.ts
      "
volumes:
  zhquiz:
