version: '3'
services:
  zhquiz:
    build:
      context: .
    environment:
      - PORT=35594
      - DATABASE_URL

      # Try randomkeygen.com
      - SECRET=7JMqUYvB4tn1RdMIBvWzUL6O4LNk7QH5

      # See https://magic.link for signing in and authorization
      - MAGIC_PUBLIC
      - MAGIC_SECRET
    ports:
      - 35594:35594 # $PORT:$PORT - Go to http://localhost:$PORT
    restart: always
    network_mode: host
