openapi: 3.0.0
info:
  contact:
    email: polv@polv.cc
    name: Pacharapol Withayasakpunt
    url: https://www.polv.cc
  description: Chinese quizzing API
  license:
    name: MIT
    url: https://mit-license.org/
  termsOfService: http://swagger.io/terms/
  title: ZhQuiz API
  version: "0.1"
security:
  - BasicAuth: []
  - FirebaseAuth: []
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    FirebaseAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  # Media routes - server/api/media.go
  /api/media/upload:
    post:
      tags: [media]
      summary: Upload media to local filesystem
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        201:
          description: Upload success
          content:
            application/json:
              schema:
                type: object
                properties:
                  url:
                    type: string
                    description: URL to load media from
                    example: /media/image.png
