[tool.poetry]
name = "zhquiz-server"
version = "0.1.0"
description = ""
authors = ["Pacharapol Withayasakpunt <polv@polv.cc>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
jieba = "^0.42.1"
wordfreq = "^2.3.2"
fastapi = "^0.61.2"
uvicorn = "^0.12.3"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
pylint = "^2.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
